default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testtask_development

test:
  <<: *default
  database: testtask_test

production:
  <<: *default
  database: testtask_production
  username: testtask
  password: <%= ENV["TESTTASK_DATABASE_PASSWORD"] %>
